version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "garage-webcam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wrm3yf5oc4gc"
s3_prefix = "garage-webcam"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
