version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "garage-webcam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g4va7yzz7uo"
s3_prefix = "garage-webcam"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
